### ISSUE TITLE
dm_draw() doesn't show unique keys

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dm#1869] opened 2023-03-30 15:56 UTC
I believe they should be shown in the compact view along with pks and fks, and at least highlighted when `view_type = "all"`

``` r
library(dm)
dm1 <- 
  dm(a = data.frame(col1=1:2, col2=3:4, col3 = 5:6)) %>% 
  dm_add_pk(a, col1) %>% 
  dm_add_uk(a, col2)
  
dm_draw(dm1)
```

![](https://i.imgur.com/DdFAE3h.png)

``` r
dm_draw(dm1, view_type = "all")
```

![](https://i.imgur.com/XupRia0.png)

<sup>Created on 2023-03-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by TSchiefer** [comment] 2023-03-30 19:56
duplicate of #1731
shall we close one of them?

**Closed** 2023-03-30 22:27 UTC
